name: ledgerly_client
description: Ledgerly Flutter client (local-first).
publish_to: none
version: 0.0.17+17
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  drift: ^2.34.3
  drift_flutter: ^0.3.1
  path_provider: ^2.1.5
  path: ^1.9.1
  uuid: ^4.5.1
  go_router: ^17.5.0
  dio: ^5.8.0+1
  flutter_secure_storage: ^11.0.0
  shared_preferences: ^2.5.3
  web: ^1.1.1
  ledger_domain:
    path: ../../packages/ledger_domain
  ledger_sync:
    path: ../../packages/ledger_sync
  file_picker: ^12.0.0
  share_plus: ^13.3.0
  local_auth: ^3.0.2
  gbk_codec: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: 2.34.0
  build_runner: ^2.4.15
  sqlite3: ^3.5.0

flutter:
  generate: true
  uses-material-design: true
