-- Tag transactions with their origin (auto-ledger, manual, recurring, ...).
--
-- The field is opaque: any short string is acceptable, but values should be
-- kept stable across releases so consumers can filter reports reliably.
-- Reserved values:
--   * auto_ledger  - created from a captured payment notification
--   * manual       - entered by the user through the UI (default, omitted)
--   * recurring    - generated by a recurring rule job
ALTER TABLE transactions
    ADD COLUMN IF NOT EXISTS source TEXT;

CREATE INDEX IF NOT EXISTS idx_transactions_book_source
    ON transactions (book_id, source)
    WHERE deleted_at IS NULL AND source IS NOT NULL;
